name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Mill
      uses: jodersky/setup-mill@v0.1.3
    - name: Build assembly
      run: mill app.assembly
    - name: Upload assembly
      uses: actions/upload-artifact@v2
      with:
        name: feederiken.jar
        path: out/app/assembly/dest/out.jar

  publish_release:

    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' &&
      startsWith(github.event.ref, 'refs/tags')
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: feederiken.jar
      - uses: actions/create-release@v1.1.1
        id: create_gh_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_gh_release.outputs.upload_url }}
          asset_path: feederiken
          asset_name: feederiken-${{ github.ref }}.jar
          asset_content_type: application/java-archive
