name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Mill
      uses: jodersky/setup-mill@v0.1.3
    - name: Build assembly
      run: mill app.assembly
    - name: Upload assembly
      uses: actions/upload-artifact@v2
      with:
        name: feederiken.jar
        path: out/app/assembly/dest/out.jar
